language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install nose --use-mirrors
  - python setup.py install
script: nosetests
notifications:
    email:
        - jcarbaugh@gmail.com